development: &development
  adapter: postgresql
  database: sobrietyforwomen_development
  username: moiseszaragoza
  host:     localhost
  port:     5432
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: sobrietyforwomen_test

cucumber:
  database: sobrietyforwomen_cucumber

