CARRIER_WAVE_ACCESS_KEY: 'AKIAIFFQMXEAA552H74A'
CARRIER_WAVE_SECRET_ACCESS_KEY: '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'
CARRIER_WAVE_BUCKET: 's4w-dev'
TWILIO_FROM_PHONE: '+9546213334'
TWILIO_ACCOUNT_SID: 'AC32a3c49700934481addd5ce1659f04d2'
TWILIO_AUTH_TOKEN:  '3e28ba418df3579e7c17e4bb9d2d1ecc'
TWILIO_API_URL:  ''
TWILIO_API_KEY:  ''
